services:
  - type: web
    name: fsams-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: LOGIN_URL
        sync: false
      - key: ORG_EMAIL_DOMAIN
        sync: false
      - key: UPLOAD_DIR
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_VALIDATION_TIMEOUT_MS
        value: "10000"
      - key: EMAIL_SEND_TIMEOUT_MS
        value: "10000"
